#端口号
server:
  port: 8080

#数据库
jdbc:
  driver-class-name: com.mysql.jdbc.Driber
  url: jdbc:mysql://127.0.0.1:3306/leyou
  username: root
  password: 1qaz@WSX

spring:
  # 激活哪一个环境的配置文件
  profiles:
    active: dev
    #active: dep
